import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import MuiThemeProvider from "@/components/theme-provider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-primary"> 
        <MuiThemeProvider>{children}</MuiThemeProvider>
      </body>
    </html>
  );
}
