import { 
  baseColors, 
  semanticColors, 
  textColors, 
  typography, 
  spacing, 
  borderRadius, 
  shadows 
} from '../tokens'

export const tailwindTheme = {
  colors: {
    primary: baseColors.primary,
    secondary: baseColors.secondary,
    blue: baseColors.blue,
    red: baseColors.red,
    neutral: baseColors.neutral,
    semantic: {
      success: semanticColors.success,
      warning: semanticColors.warning,
      error: semanticColors.error,
      info: semanticColors.info,
      surface: semanticColors.surface,
      'surface-alt': semanticColors.surfaceAlt,
      background: semanticColors.background,
      border: semanticColors.border,
      'border-strong': semanticColors.borderStrong,
    },
    text: textColors,
  },
  fontFamily: {
    primary: typography.fontFamily.primary,
  },
  fontSize: {
    xs: typography.fontSize.xs,
    sm: typography.fontSize.sm,
    base: typography.fontSize.base,
    md: typography.fontSize.md,
    lg: typography.fontSize.lg,
    xl: typography.fontSize.xl,
    '2xl': typography.fontSize['2xl'],
    '3xl': typography.fontSize['3xl'],
    '4xl': typography.fontSize['4xl'],
  },
  fontWeight: {
    extralight: typography.fontWeight.extralight,
    light: typography.fontWeight.light,
    normal: typography.fontWeight.normal,
    medium: typography.fontWeight.medium,
    semibold: typography.fontWeight.semibold,
    bold: typography.fontWeight.bold,
    extrabold: typography.fontWeight.extrabold,
    black: typography.fontWeight.black,
  },
  lineHeight: {
    none: typography.lineHeight.none,
    tight: typography.lineHeight.tight,
    snug: typography.lineHeight.snug,
    normal: typography.lineHeight.normal,
    relaxed: typography.lineHeight.relaxed,
    loose: typography.lineHeight.loose,
    'xs': typography.lineHeight['xs'],
    'sm': typography.lineHeight['sm'],
    'base': typography.lineHeight['base'],
    'md': typography.lineHeight['md'],
    'lg': typography.lineHeight['lg'],
    'xl': typography.lineHeight['xl'],
  },
  letterSpacing: {
    tighter: typography.letterSpacing.tighter,
    tight: typography.letterSpacing.tight,
    normal: typography.letterSpacing.normal,
    wide: typography.letterSpacing.wide,
    wider: typography.letterSpacing.wider,
    widest: typography.letterSpacing.widest,
  },
  spacing: {
    0: spacing['0'],
    1: spacing['1'],
    2: spacing['2'],
    3: spacing['3'],
    4: spacing['4'],
    5: spacing['5'],
    6: spacing['6'],
    8: spacing['8'],
    10: spacing['10'],
    12: spacing['12'],
    14: spacing['14'],
    16: spacing['16'],
    20: spacing['20'],
  },
  borderRadius: {
    sm: borderRadius.sm,
    md: borderRadius.md,
    lg: borderRadius.lg,
    xl: borderRadius.xl,
    '2xl': borderRadius['2xl'],
    '3xl': borderRadius['3xl'],
    '4xl': borderRadius['4xl'],
  },
  boxShadow: {
    sm: shadows.sm,
    md: shadows.md,
  },
}
