import { createTheme } from '@mui/material/styles'
import { 
  baseColors, 
  semanticColors, 
  textColors, 
  typography, 
  borderRadius, 
  shadows,
  domainColors 
} from '../tokens'
import { muiComponentOverrides } from './components'

export const muiTheme = createTheme({
  palette: {
    primary: {
      main: baseColors.primary[500],
      light: baseColors.primary[300],
      dark: baseColors.primary[700],
      contrastText: '#ffffff',
      // Extended palette for all shades
      50: baseColors.primary[50],
      100: baseColors.primary[100],
      200: baseColors.primary[200],
      300: baseColors.primary[300],
      400: baseColors.primary[400],
      500: baseColors.primary[500],
      600: baseColors.primary[600],
      700: baseColors.primary[700],
      800: baseColors.primary[800],
      900: baseColors.primary[900],
    },
    secondary: {
      main: baseColors.secondary[500],
      light: baseColors.secondary[300],
      dark: baseColors.secondary[700],
      contrastText: '#ffffff',
      // Extended palette
      50: baseColors.secondary[50],
      100: baseColors.secondary[100],
      200: baseColors.secondary[200],
      300: baseColors.secondary[300],
      400: baseColors.secondary[400],
      500: baseColors.secondary[500],
      600: baseColors.secondary[600],
      700: baseColors.secondary[700],
      800: baseColors.secondary[800],
      900: baseColors.secondary[900],
    },
    info: {
      main: baseColors.blue[500],
      light: baseColors.blue[300],
      dark: baseColors.blue[700],
      contrastText: '#ffffff',
      // Extended palette
      50: baseColors.blue[50],
      100: baseColors.blue[100],
      200: baseColors.blue[200],
      300: baseColors.blue[300],
      400: baseColors.blue[400],
      500: baseColors.blue[500],
      600: baseColors.blue[600],
      700: baseColors.blue[700],
      800: baseColors.blue[700],
      900: baseColors.blue[700],
    },
    error: {
      main: baseColors.red[500],
      light: baseColors.red[300],
      dark: baseColors.red[700],
      contrastText: '#ffffff',
      // Extended palette
      50: baseColors.red[50],
      100: baseColors.red[100],
      200: baseColors.red[200],
      300: baseColors.red[300],
      400: baseColors.red[400],
      500: baseColors.red[500],
      600: baseColors.red[600],
      700: baseColors.red[700],
      800: baseColors.red[800],
      900: baseColors.red[900],
    },
    warning: {
      main: semanticColors.warning,
      light: baseColors.secondary[300],
      dark: baseColors.secondary[700],
    },
    success: {
      main: semanticColors.success,
      light: baseColors.primary[300],
      dark: baseColors.primary[700],
    },
    background: {
      default: semanticColors.background,
      paper: semanticColors.surface,
    },
    text: {
      primary: textColors.primary,
      secondary: textColors.secondary,
    },
    divider: semanticColors.border,
  },
  typography: {
    fontFamily: typography.fontFamily.primary,
    // Standard MUI typography with enhanced scalability
    h1: {
      fontSize: typography.fontSize['4xl'],
      fontWeight: typography.fontWeight.bold,
      lineHeight: typography.lineHeight['xl'],
      letterSpacing: typography.letterSpacing.tight,
    },
    h2: {
      fontSize: typography.fontSize['3xl'],
      fontWeight: typography.fontWeight.bold,
      lineHeight: typography.lineHeight['xl'],
      letterSpacing: typography.letterSpacing.tight,
    },
    h3: {
      fontSize: typography.fontSize['2xl'],
      fontWeight: typography.fontWeight.semibold,
      lineHeight: typography.lineHeight['lg'],
      letterSpacing: typography.letterSpacing.tight,
      textTransform: 'uppercase',
    },
    h4: {
      fontSize: typography.fontSize.xl,
      fontWeight: typography.fontWeight.semibold,
      lineHeight: typography.lineHeight['lg'],
      letterSpacing: typography.letterSpacing.tight,
    },
    h5: {
      fontSize: typography.fontSize.lg,
      fontWeight: typography.fontWeight.semibold,
      lineHeight: typography.lineHeight.md,
      letterSpacing: typography.letterSpacing.normal,
    },
    h6: {
      fontSize: typography.fontSize.md,
      fontWeight: typography.fontWeight.semibold,
      lineHeight: typography.lineHeight.md,
      letterSpacing: typography.letterSpacing.normal,
    },
    subtitle1: {
      fontSize: typography.fontSize.md,
      fontWeight: typography.fontWeight.medium,
      lineHeight: typography.lineHeight.normal,
      letterSpacing: typography.letterSpacing.normal,
    },
    subtitle2: {
      fontSize: typography.fontSize.sm,
      fontWeight: typography.fontWeight.medium,
      lineHeight: typography.lineHeight.sm,
      letterSpacing: typography.letterSpacing.normal,
    },
    body1: {
      fontSize: typography.fontSize.base,
      fontWeight: typography.fontWeight.normal,
      lineHeight: typography.lineHeight.base,
      letterSpacing: typography.letterSpacing.normal,
    },
    body2: {
      fontSize: typography.fontSize.sm,
      fontWeight: typography.fontWeight.normal,
      lineHeight: typography.lineHeight.sm,
      letterSpacing: typography.letterSpacing.normal,
    },
    button: {
      fontSize: typography.fontSize.sm,
      fontWeight: typography.fontWeight.semibold,
      lineHeight: typography.lineHeight.tight,
      letterSpacing: typography.letterSpacing.tight,
      textTransform: 'none',
    },
    caption: {
      fontSize: typography.fontSize.xs,
      fontWeight: typography.fontWeight.normal,
      lineHeight: typography.lineHeight.xs,
      letterSpacing: typography.letterSpacing.normal,
    },
    overline: {
      fontSize: typography.fontSize.xs,
      fontWeight: typography.fontWeight.semibold,
      lineHeight: typography.lineHeight.none,
      letterSpacing: typography.letterSpacing.wide,
      textTransform: 'uppercase',
    },
  },
  shape: {
    borderRadius: borderRadius['3xl'],
  },
  components: muiComponentOverrides,
  shadows: [
    'none',
    '0 1px 2px rgba(0, 0, 0, 0.05)',
    shadows.sm,
    '0 4px 6px rgba(15,31,20,0.07)',
    '0 4px 8px rgba(15,31,20,0.08)',
    '0 4px 10px rgba(15,31,20,0.09)',
    '0 4px 14px rgba(15,31,20,0.1)',
    '0 4px 18px rgba(15,31,20,0.11)',
    '0 6px 10px rgba(15,31,20,0.12)',
    '0 6px 14px rgba(15,31,20,0.13)',
    '0 6px 18px rgba(15,31,20,0.14)',
    '0 6px 22px rgba(15,31,20,0.15)',
    '0 8px 16px rgba(15,31,20,0.12)',
    '0 8px 20px rgba(15,31,20,0.13)',
    '0 8px 24px rgba(15,31,20,0.14)',
    '0 10px 20px rgba(15,31,20,0.13)',
    '0 10px 24px rgba(15,31,20,0.14)',
    '0 10px 28px rgba(15,31,20,0.15)',
    '0 12px 24px rgba(15,31,20,0.14)',
    '0 12px 28px rgba(15,31,20,0.15)',
    '0 12px 32px rgba(15,31,20,0.16)',
    '0 14px 28px rgba(15,31,20,0.15)',
    '0 14px 32px rgba(15,31,20,0.16)',
    '0 14px 36px rgba(15,31,20,0.17)',
    '0 16px 32px rgba(15,31,20,0.16)',
  ],
})
